// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBklYdQTycM9rw95lp5iNiMf7diJKcPQlA',
    appId: '1:675846533749:web:55a83fba26089adb997e3c',
    messagingSenderId: '675846533749',
    projectId: 'pjtrg-804c3',
    authDomain: 'pjtrg-804c3.firebaseapp.com',
    storageBucket: 'pjtrg-804c3.firebasestorage.app',
    measurementId: 'G-L807NVHSD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8myR4OGuZObxfyBhLjBGcHuXnuekLWgw',
    appId: '1:675846533749:android:18db7c88ac991a04997e3c',
    messagingSenderId: '675846533749',
    projectId: 'pjtrg-804c3',
    storageBucket: 'pjtrg-804c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kwXCJzls3fVxmrFRCkoW7_tchBdSyEA',
    appId: '1:675846533749:ios:3ae2df6fe75cee9d997e3c',
    messagingSenderId: '675846533749',
    projectId: 'pjtrg-804c3',
    storageBucket: 'pjtrg-804c3.firebasestorage.app',
    iosBundleId: 'com.example.rankingGroundV1',
  );
}
